### ISSUE TITLE
[Question] Will this be getting a Gen 7 Update?

### ISSUE THREAD

**Issue by greenDarkness** [Hidden50/brmt#3]
Hello there!
Your tool is extremely useful, and I was wondering if you were planning on updating it?
Thank you!

**Comment by Hidden50** [comment]
Hi!
I've been working on a gen7 version for a long while now. Unfortunately other projects demand my attention, but I hope to finish this soon.

In the meantime, there is a beta version for gen7. It's still missing a UI for selecting the team, so this needs to be done via the javascript console if you want to use it already.

hidden50.github.io/brmt/beta/index.html

**Comment by greenDarkness** [comment]
That's the best news I've heard all week. 
Do you mind if I pry and ask what else you're working on?

I would absolutely love to test it. Thank you for sharing!

**Comment by Hidden50** [comment]
The first step of the rewrite is finally here. Not much of a visible difference at all, but the code's gotten a lot more readable and easier to maintain.

(Edit: If you're reading the code, have a look at http://hidden50.github.io/brmt/beta/js/test.html -- it's a small object inspector that gives an overview over the project.)

Something else I've been working on, would be a more flexible approach to damage calcs. I've often manually done calcs like "chance to 3hko with one crit", etc. I've written some code to easily do those calcs, but there's currently no interface for it; so I can't quite add that code to the calculator yet.

**Comment by greenDarkness** [comment]
Very very nice! Progress is progress. 

I understand the logic, but I'm not very programming language literate yet.

Yeah, parts like that are a very nice touch, especially for use in draft format (which is what I mostly play).
I really like the way the tool is shaping up. The item icons, and set descriptions are a fantastic touch. 
Can't wait for the team selection update so that testing can begin!
